services:
  notes-mysql:
    image: mysql:9.2.0
    container_name: notes-mysql
    env_file:
      - kustomize/base/secrets/mysql.env
    ports:
      - 3309:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notes

  notes-minio:
    image: minio/minio:latest
    container_name: notes-minio
    command: server --console-address ":9001" /data
    env_file: kustomize/base/secrets/minio.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    networks:
      - notes

  notes-app:
    image: ghcr.io/alexanderboldt/notes:3.1.0
    container_name: notes-app
    ports:
      - 4000:4000
    env_file:
      - kustomize/base/secrets/mysql.env
      - kustomize/base/secrets/notes.env
    depends_on:
      - notes-mysql
      - notes-minio
    networks:
      - notes

volumes:
  mysql_data:
  minio_data:

networks:
  notes:
    name: notes
