services:
  notes-mysql:
    image: mysql:9.2.0
    container_name: notes-mysql
    env_file:
      - kustomize/base/secrets/mysql.env
    ports:
      - 3309:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notes

  notes-app:
    image: ghcr.io/alexanderboldt/notes:3.0.0
    container_name: notes-app
    ports:
      - 4000:4000
    env_file:
      - kustomize/base/secrets/mysql.env
      - kustomize/base/secrets/notes.env
    depends_on:
      - notes-mysql
    networks:
      - notes

volumes:
  mysql_data:

networks:
  notes:
    name: notes
