services:
  mysql:
    image: mysql:9.2.0
    container_name: notes-mysql
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notes

  app:
    image: notes/app:1.0.0
    container_name: notes-app
    ports:
      - 4000:4000
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${DB}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - notes

volumes:
  mysql_data:

networks:
  notes:
    name: notes
