ktor:
  profile: ${KTOR_PROFILE:prod}
  application:
    modules:
      - org.alex.notes.ApplicationKt.module
  deployment:
    port: 4000

database:
  url: ${MYSQL_URL}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}

s3:
  accessKey: ${S3_ACCESS_KEY:null}
  secretKey: ${S3_SECRET_KEY:null}
  host: ${S3_HOST:null}
  port: ${S3_PORT:null}
  region: ${S3_REGION}
