ktor:
  application:
    modules:
      - org.alex.notes.ApplicationKt.module
  deployment:
    port: 4000

database:
  url: ${MYSQL_URL}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}

s3:
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
  host: ${S3_HOST}
  port: ${S3_PORT}
  region: ${S3_REGION}
