apiVersion: 1

datasources:
  - name: notes
    uid: df95d61129vy8b
    type: mysql
    url: mysql:3306
    user: ${MYSQL_USER}
    access: proxy
    jsonData:
      database: ${MYSQL_DATABASE}
      sslmode: disable
    secureJsonData:
      password: ${MYSQL_PASSWORD}
