apiVersion: 1

datasources:
  - name: notes
    uid: df95d61129vy8b
    type: mysql
    url: mysql:3306
    user: ${DB_USERNAME}
    access: proxy
    jsonData:
      database: ${DB}
      sslmode: disable
    secureJsonData:
      password: ${DB_PASSWORD}
