apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  namespace: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
        - name: notes
          image: localhost:32000/notes/app:1.0.0
          envFrom:
            - configMapRef:
                name: notes-config
            - secretRef:
                name: notes-secret
          ports:
            - containerPort: 4000
