apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  selector:
    matchLabels:
      app: notes
  replicas: 1
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
        - name: notes
          image: localhost:32000/notes/app:2.0.0
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 4000
