namespace: notes

resources:
  - namespace.yml
  - mysql/statefulset.yml
  - mysql/service.yml
  - notes/deployment.yml
  - notes/service.yml

secretGenerator:
  - name: mysql-secret
    envs:
      - secrets/mysql.env
  - name: notes-secret
    envs:
      - secrets/notes.env
