namespace: notes

resources:
  - namespace.yml
  - mysql/statefulset.yml
  - notes/deployment.yml

secretGenerator:
  - name: notes-mysql-secret
    envs:
      - secrets/mysql.env
  - name: notes-app-secret
    envs:
      - secrets/notes.env
