namespace: notes

resources:
  - namespace.yml
  - mysql/statefulset.yml
  - mysql/service.yml
  - notes/deployment.yml
  - notes/service.yml

secretGenerator:
  - name: mysql-secret
    literals:
      - MYSQL_DATABASE=notes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
  - name: notes-secret
    literals:
      - DB_URL=jdbc:mysql://mysql:3306/notes
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
